version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${KAFKA_HOST}"
      KAFKA_CREATE_TOPICS: "${KAFKA_TOPICS}"
      KAFKA_ZOOKEEPER_CONNECT: "${ZOOKEEPER_HOST}:${ZOOKEEPER_PORT}"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge